apiVersion: ibmcloud.ibm.com/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: cosbadspec-1
spec:
  source:
    serviceClass: cloud-object-storage
    serviceID: 1cdd19ff-c033-4767-b6b7-4fe2fc58c6a1
    resourceGroup: Default
  roles:
    - Reader
  target:
    serviceClass: kms