apiVersion: ibmcloud.ibm.com/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: coskmsauthpolicy
spec:
  source:
    serviceClass: cloud-object-storage
  roles:
    - Reader
  target:
    serviceClass: kms
